### ISSUE TITLE
计划维护

### ISSUE THREAD

**Issue by cjc7373** [NWUCA/NWU.ICU#14]
1. 增加一个 dns 测试解析, 如 test.nwu.icu
2. 修改 caddy 配置进入维护模式 (nwu.icu 指向维护页面, test.nwu.icu 指向网站)
3. 生产环境更新版本
4. 爬教务系统
5. 迁移原有课程
6. 测试
7. 修改 caddy 配置, 退出维护模式

**Comment by lincww** [comment]
require feat: backup
