### ISSUE TITLE
what is PR meaning 

### ISSUE THREAD

**Issue by accountl** [NWUCA/NWU.ICU#16]
"贡献
欢迎提 PR 或 issue."

**Comment by cjc7373** [comment]
简而言之, PR 就是 Pull Request, 当你在自己的分支写了一些代码之后, 你可以创建一个 PR 请求主仓库的维护者合并你的分支, PR 也是维护者们进行代码评审 (review) 的主要手段.

更详细的解释可以看 Pro Git 这本书.
