### ISSUE TITLE
缺少文化遗产学院资料

### ISSUE THREAD

**Issue by juzizhiyun** [NWUCA/NWU.ICU#18]
如果可以建立文化遗产学院课程我可以尝试提供复习资料

**Comment by MooWantFree** [comment]
> 如果可以建立文化遗产学院课程我可以尝试提供复习资料

抱歉, 因为没有相关投稿所以一直未建立文遗学院的课程文件夹, 如果可以的话, 发送文件到contribute#nwu.icu(替换#为@), 十分感谢

**Comment by MooWantFree** [comment]
> 被退回 &nbsp; lck ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年6月18日(星期二) 中午11:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [NWUCA/NWU.ICU] 缺少文化遗产学院资料 (Issue #18) 如果可以建立文化遗产学院课程我可以尝试提供复习资料 抱歉, 因为没有相关投稿所以一直未建立文遗学院的课程文件夹, 如果可以的话, 发送文件到contribute#nwu.icu(替换#为@), 十分感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

十分抱歉, 请尝试admin#nwu.icu(替换#为@), 如仍无法发送请留言

**Comment by MooWantFree** [comment]
已在邮件中回复, 其中部分文件打开失败, 期待阁下可以确认一下文件完整性.
已将阁下发送的文件上传到网站

**Comment by MooWantFree** [comment]
由于阁下长时间未回复邮件以及issue, 将关闭此issue
